name: container

on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: shereenfarag/alpine-squid-proxy:squid5
      ports:
        - 8081
    steps:
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: ps
        run: ps
